# Generated by Django 2.0.2 on 2019-04-12 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmString',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=256, verbose_name='注册码')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='注册码的生成时间')),
            ],
            options={
                'db_table': 't_confirmString',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='用户名')),
                ('password', models.CharField(max_length=40, verbose_name='密码')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='用户的创建时间')),
                ('has_confirm', models.BooleanField(default=False, verbose_name='邮箱是否确认')),
            ],
            options={
                'db_table': 't_user',
            },
        ),
        migrations.AddField(
            model_name='confirmstring',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='demo.User', verbose_name='关联的用户'),
        ),
    ]
